parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     proj_symfony
    database_user:     root
    database_password: ~
    # You should uncomment this if you want use pdo_sqlite
    # database_path: "%kernel.root_dir%/data.db3"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    # A secret key that's used to generate certain security-related tokens
    secret:            rsCyTagn333

    session.name: SOCIAL_NETWORK_SESSION
    session.remember_me.name: SOCIAL_NETWORK_LONG_SESSION
