services:
#    acme_task.example:
#        class: Acme\TaskBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  acme_demo.form.type.task:
      class: Acme\TaskBundle\Form\Type\TaskType
      tags:
        - { name: form.type, alias: task }